# Use root/example as user/password credentials
version: '3.8'

services:

  db:
    image: mysql:8.0.23
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: test
      MYSQL_USER: nim
      MYSQL_PASSWORD: nim